stages:
  - build

build:
  image: docker:git
  services:
  - docker:dind
  stage: build
  before_script:
    - apk add bash
  script:
    - ./run_docker --pre-built make
  artifacts:
    paths:
    - comlink/dist
    - build
    expire_in: 1 week

