package:
  name: pycrfsuite
  version: 0.9.7
source:
  url: https://files.pythonhosted.org/packages/e1/4d/abbe0dc125b0a11ecd55fa3a5b33b44656227d214a61deb73e2a152aa257/python-crfsuite-0.9.7.tar.gz

#  patches:
#   - patches/setitup.patch
#  extras:
#   -
#      - src/setup.cfg
#      - ./setup.cfg
#build:
#  cflags: -s USE_ZLIB=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1
#  ldflags: -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -ljpeg
test:
  imports:
  - pycrfsuite
