package:
  name: reportlab
  version: 3.6.2
source:
  url: https://files.pythonhosted.org/packages/ae/4e/5777c95f93d85854cc9da0627636d2c3982be55a7b9cfc34d1a53e9a9c99/reportlab-3.6.2.tar.gz
  patches:
  - patches/setup.patch

build:
  cflags: -DCMAKE_SIZEOF_VOID=4

test:
  imports:
  - reportlab
